### ISSUE TITLE
Remove unnecessary explicit dependencies

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/terraform-google-out-of-band-security#3]
For example `google_compute_region_autoscaler.main` does not need to depend on `google_compute_region_instance_group_manager.main` as it has an implicit dependency via `google_compute_region_instance_group_manager.main.id` which is a computed attribuite.

**Comment by Saipriyavk** [comment]
Fixed without having to create a PR. Please let me know if a PR was necessary. Thanks!
